board: sam9x60: uboot-env: increase the cma size
To resolve following issues on sam9x60 boards with the plane and egt-boards
applications, sometime with egt-easing, increase cma size to 16m.

- planes -c /usr/share/planes/parallax.config: the ninja sprite is not
  displayed at all
- egt-boards: the blue side panel is wrongly drawn on top of other side
  panels
- egt-easing: the balloon is wrongly drawn on top of the side panel

$ LIBPLANES_DEBUG=1 egt_boards
$ LIBPLANES_DEBUG=1 egt_easing
$ LIBPLANES_DEBUG=1 planes -c /usr/share/planes/parallax.config

error: failed to create fb

All those issues are due to libplanes failling to allocate frame buffers
for overlays. Hence, with EGT applications, some graphics elements are
placed into the primary plane instead of being placed into dedicated
overlays.

Incrementing the cma value on the kernel command line in u-box fixes the
issues:
- cma=8m: KO
- cma=12m: KO
- cma=16m: OK

Signed-off-by: Nayab Sayed <nayabbasha.sayed@microchip.com>
Reviewed-by: Hari Prasath Gujulan Elango <hari.prasathge@microchip.com>
Signed-off-by: Jamie Gibbons <jamie.gibbons@microchip.com>