package/wilc_firmware: fix license file name
File name was changed in package by commit:
2400007a8a4 ("Fix typo in license file name")

This causes an error for the license of this package:

>>> wilc_firmware wilc_linux_15_5rc2 Collecting legal info
sha256sum: ***/buildroot-at91/output/build/wilc_firmware-wilc_linux_15_5rc2/LICENCE.wilc_fw: No such file or directory
ERROR: LICENCE.wilc_fw has wrong sha256 hash:
ERROR: expected: 71355eee947a312594dbdaac039827544f93d23949b65c356b7b0ce09e2600fb
ERROR: got     :
ERROR: Incomplete download, or man-in-the-middle (MITM) attack

Fix the file name accordingly.

Signed-off-by: Eugen Hristev <eugen.hristev@microchip.com>