libplanes: fix building in some buildroot configurations
In some buildroot configurations, like using local.mk to override the srcdir,
libplanes fails to build because it needs a patched libtool.

    ERROR: unsafe header/library path used in cross-compilation: '-L/usr/lib'

Signed-off-by: Joshua Henderson <joshua.henderson@microchip.com>